import { db } from '@/db';
import { profiles, resources, posts } from '@/db/schema';
const photo = (id: string, w = 700) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;
export async function seed() {
  await db.insert(profiles).values([
    { id: 'ananya', name: 'Ananya', age: 25, city: 'Bengaluru', distance: 3, bio: 'Designing a life full of little adventures. Usually found in a bookstore or discovering a new café. Let’s trade playlists?', intent: 'Relationship', interests: ['Travel', 'Coffee', 'Design'], image: photo('34324403'), verified: true, online: true, compatibility: 96 },
    { id: 'riya', name: 'Riya', age: 24, city: 'Bengaluru', distance: 5, bio: 'A little sunshine, a lot of curiosity. Weekend hikes, good food, and conversations that go beyond “hey”.', intent: 'Friendship', interests: ['Music', 'Hiking', 'Foodie'], image: photo('36918310'), verified: true, online: true, compatibility: 92 },
    { id: 'meera', name: 'Meera', age: 26, city: 'Bengaluru', distance: 7, bio: 'Product marketer by day, amateur chef by night. Looking for someone who appreciates slow Sundays and a good story.', intent: 'Relationship', interests: ['Reading', 'Fitness', 'Art'], image: photo('17827869'), verified: true, online: false, compatibility: 89 },
    { id: 'arjun', name: 'Arjun', age: 28, city: 'Bengaluru', distance: 4, bio: 'Photographer, coffee enthusiast, and your next badminton partner. New to the city and making it home, one connection at a time.', intent: 'Activity partners', interests: ['Photography', 'Coffee', 'Badminton'], image: photo('1043474'), verified: true, online: true, compatibility: 87 },
    { id: 'isha', name: 'Isha', age: 27, city: 'Mumbai', distance: 12, bio: 'Collecting moments, not things. Live music, weekend markets, and meeting kind people.', intent: 'Friendship', interests: ['Music', 'Travel', 'Art'], image: photo('37798732'), verified: true, online: false, compatibility: 85 },
    { id: 'kabir', name: 'Kabir', age: 29, city: 'Delhi', distance: 9, bio: 'Building things and finding my people. Always up for a food walk or a thoughtful conversation.', intent: 'Relationship', interests: ['Foodie', 'Design', 'Travel'], image: photo('614810'), verified: false, online: false, compatibility: 83 },
  ]).onConflictDoNothing();
  await db.insert(resources).values([
    { id: 'coffee-club', kind: 'community', ownerId: 'seed', title: 'Bengaluru Coffee Club', description: 'Good coffee. Better conversations. Discover hidden cafés and meet fellow coffee lovers across the city.', category: 'Food & drink', city: 'Bengaluru', image: photo('1036444'), members: 1248, capacity: 10000, location: 'Across Bengaluru' },
    { id: 'weekend-explorers', kind: 'community', ownerId: 'seed', title: 'Weekend Explorers', description: 'Swap your screens for green scenes. A friendly bunch exploring trails, sunrise spots, and places less travelled.', category: 'Outdoors', city: 'Bengaluru', image: photo('1271619'), members: 856, capacity: 10000, location: 'Bengaluru & beyond' },
    { id: 'creative-corner', kind: 'community', ownerId: 'seed', title: 'The Creative Corner', description: 'A little space for big ideas. Art, design, photography, and the people who make things happen.', category: 'Art & culture', city: 'Bengaluru', image: photo('1266808'), members: 642, capacity: 10000, location: 'Indiranagar' },
    { id: 'books-and-brews', kind: 'community', ownerId: 'seed', title: 'Books & Brews', description: 'One book, a warm cup, and a circle of thoughtful people. Monthly reads and relaxed Sunday discussions.', category: 'Books', city: 'Bengaluru', image: photo('159711'), members: 328, capacity: 10000, location: 'Koramangala' },
    { id: 'sunset-social', kind: 'event', ownerId: 'seed', title: 'Sunset, sips & new connections', description: 'An easygoing rooftop evening with good music, icebreakers, and people you haven’t met yet. Come as you are. Leave with a new connection. Hosted at a public venue, with a Zivora community host on-site.', category: 'Social mixer', city: 'Bengaluru', image: photo('4878006'), members: 24, capacity: 40, location: 'Skyye, UB City · Bengaluru', date: '2026-07-18T17:30' },
    { id: 'cubbon-walk', kind: 'event', ownerId: 'seed', title: 'Sunday stroll at Cubbon Park', description: 'Start your Sunday with a gentle walk, fresh air, and fresh faces. All fitness levels welcome. Meet by the public library entrance.', category: 'Outdoors', city: 'Bengaluru', image: photo('1271619'), members: 18, capacity: 30, location: 'Cubbon Park · Bengaluru', date: '2026-07-19T07:00' },
    { id: 'clay-and-conversations', kind: 'event', ownerId: 'seed', title: 'Clay & conversations', description: 'Get your hands messy and meet creative souls. A beginner-friendly pottery workshop with materials and a cup of chai included.', category: 'Art & culture', city: 'Bengaluru', image: photo('1266808'), members: 12, capacity: 20, location: 'Clay Station, Indiranagar', date: '2026-07-25T11:00' },
    { id: 'creator-aisha', kind: 'creator', ownerId: 'seed', title: 'Aisha Creates', description: 'Making art approachable, one conversation at a time. Join my weekly creative circle for honest conversations about living a creative life.', category: 'City Creator', city: 'Bengaluru', image: photo('34324403'), members: 2400, capacity: 100000, location: 'Art & thoughtful living' },
    { id: 'creator-rohan', kind: 'creator', ownerId: 'seed', title: 'Roaming with Rohan', description: 'Your friendly guide to the places and people that make Bengaluru special. Community walks every other Sunday.', category: 'Local Creator', city: 'Bengaluru', image: photo('1043474'), members: 1800, capacity: 100000, location: 'Travel & local stories' },
  ]).onConflictDoNothing();
  await db.insert(posts).values([
    { id: 'post-coffee-1', resourceId: 'coffee-club', userId: 'seed', author: 'Ananya S.', text: 'Found the loveliest little café in Indiranagar today! Anyone up for a filter coffee crawl this weekend? ☕' },
    { id: 'post-weekend-1', resourceId: 'weekend-explorers', userId: 'seed', author: 'Arjun M.', text: 'Planning a sunrise walk at Nandi Hills. Beginners welcome — it’s all about the company, not the pace. 🌿' },
    { id: 'post-creative-1', resourceId: 'creative-corner', userId: 'seed', author: 'Meera K.', text: 'Our next sketch & chai session is taking shape. Bring any materials you enjoy and your curiosity! 🎨' },
  ]).onConflictDoNothing();
}
